# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: server # Use an image built from the specified dockerfile in the `server` directory.
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redisearch # This service depends on redisearch. Start that first.
    environment: # Pass environment variables to the service
      SPRING_REDIS_HOST: redisearch
      STOMP_PORT: 80 
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  client:
    build:
      context: client # Use an image built from the specified dockerfile in the `client` directory.
      dockerfile: Dockerfile
    ports:
      - "80:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - server
    networks:
      - frontend

  # RediSearch Service
  redisearch:
    image: redislabs/redisearch:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend: