version: '3.7'

services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redisearch
    environment:
      SPRING_REDIS_HOST: redisearch
      STOMP_PORT: 80 
    networks:
      - backend
      - frontend

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - server
    networks:
      - frontend

  redisearch:
    image: redislabs/redisearch:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
  frontend:
